server:
  port: 8081

spring:
  application:
    name: provider-service

dubbo:
  application:
    name: provider-dubbo-service
  registry:
    address: nacos://localhost:8848  # Nacos 注册中心地址
    group: default-dubbo
    parameters:
      namespace: default-dubbo
  protocol:
    name: dubbo
    port: 20880  # Dubbo 服务端口